### ISSUE TITLE
Position from preferred resolution gets overwritten when the current resolution changes.

### ISSUE THREAD

**Issue by Serfrost** [chalkos/RepairMe#11]
Ideally it should remember the position of each resolution used, however going to any other resolution will shift the UI elements into undesired positions and result in having to manually move them again.  For the time being I've decided to disable this plugin since my resolution switches based on the display in use.

**Comment by chalkos** [comment]
Is there any plugin that you know that handles this in a satisfactory way?

**Comment by Serfrost** [comment]
> 
> 
> Is there any plugin that you know that handles this in a satisfactory way?

I couldn't say since I don't use very many plugins nor do I develop any, but I'd be surprised if there wasn't a way to do so.  Maybe asking in the Dalamud community specifically could yield a potential fix.

**Comment by chalkos** [comment]
#7, when done, will allow you to set different profiles for different resolutions

**Comment by Serfrost** [comment]
Sounds like a good solution. Hopefully this can be adopted by other UI plugins.

**Comment by chalkos** [comment]
I actually did it in a different way. If you grab the testing version you can try it out
