### ISSUE TITLE
[Suggestion] Display Spirtitbonded item in Inventory window

### ISSUE THREAD

**Issue by Tusky** [chalkos/RepairMe#14]
It would be nice if the spiritbonded item on the equipment screen would be marked somehow, either a duplicate bar next to the durability bar, under the icon, on top of the icon to track progress. Or just an extra icon/changing color of the icon to mark it as complete, when it reaches 100%.

I understand if it's not something this plugin should implement though.

**Comment by chalkos** [comment]
The game already provides something like this
![image](https://user-images.githubusercontent.com/98429/145778979-29188f63-33de-48f1-866a-5dfd1b446324.png)

When spiritbond is complete, one of the dots (corresponding to the slot that has the full spiritbond item) becomes white.

If you're looking for a quick way to extract materia, you can also drag the "Materia Extraction" action onto your bars and use that (get it from Character (the menu button) -> Actions&Traits -> General section)
![image](https://user-images.githubusercontent.com/98429/145779581-46c4ed6f-ff1d-4d4c-a2e1-8d2ac6b22416.png)

click and done, doesn't get simpler than that

**Comment by Tusky** [comment]
I'm aware of the in-game ways, it'd be just more convenient to see it on the item right away on the character page without having to cross-reference the icons on the inventory widget :)

It's a small QoL update, but feel free to close this!

**Comment by PrincessRTFM** [comment]
Doesn't it already do that? I thought the spiritbond bar next to items on your character window turned white when it was full.

**Comment by Tusky** [comment]
No, that would be great, the bar is the durability bar next to the item. This is how it looks when you are spiritbound with an item:

![image](https://user-images.githubusercontent.com/1206970/145911163-09f2e4f2-7230-4272-a86d-2e69a3ff9f88.png)

Both rings are identical because they are above 100% in durability. But if you were look at this:
![image](https://user-images.githubusercontent.com/1206970/145911403-2fe54fe2-5dbf-4e15-9c4e-99e6adca0a49.png)

**Comment by chalkos** [comment]
This seems out of scope for this plugin, sorry. I'd recomend you create a suggestion for this here: https://github.com/goatcorp/suggestions
