### ISSUE TITLE
[Suggestion] Open Materia Creation In-Game Interface Upon Clicking 'Spiritbond Complete' Alert

### ISSUE THREAD

**Issue by borkmaster12** [chalkos/RepairMe#15]
When clicking the 'Spiritbond Complete' alert, open the same in-game interface as when executing the General action 'Materia Extraction'.

**Comment by PrincessRTFM** [comment]
Addendum: allow toggling the click-through mode of the alert such that this only applies if enabled.

**Comment by imgidedin** [comment]
Yes please, this would be great.

**Comment by chalkos** [comment]
https://github.com/goatcorp/DalamudPlugins/pull/2350
