### ISSUE TITLE
[Suggestion] Open 'Repairs' In-Game Interface Upon Clicking Condition Low/Critical Alert

### ISSUE THREAD

**Issue by borkmaster12** [chalkos/RepairMe#16]
When clicking the 'Condition is low' / 'Condition is critical' alert, open the same in-game interface as when executing the General action 'Repair'.

**Comment by PrincessRTFM** [comment]
Addendum: allow toggling the click-through mode of the alert such that this only applies if enabled.

**Comment by chalkos** [comment]
https://github.com/goatcorp/DalamudPlugins/pull/2350
