### ISSUE TITLE
[Suggestion] Option to toggle visability based on durability/spirtbond

### ISSUE THREAD

**Issue by Aceman67** [chalkos/RepairMe#17]
Can we get a visibility toggle based on Durability/SB alert threshold?

**Comment by chalkos** [comment]
You can set the bar color to fully transparent. Does that do what you want?

**Comment by Aceman67** [comment]
No, having a toggle to have it only show when your gear needs attention would be nice.

**Comment by chalkos** [comment]
I don't understand how that does not do what you ask for. what do you want to toggle the visibility of? isn't it the condition/sb bar?

**Comment by Aceman67** [comment]
There's no option to toggle visibility, only transparency. Having an option to have it not display unless the gear is below 50% (or adjustable), or when spirit bond is 100%. would be beneficial and not clutter the UI

**Comment by chalkos** [comment]
you didnt answer my question.  what do you want to toggle the visibility of?
