### ISSUE TITLE
[Suggestion] Spiritbond Percentage/Bar based on lowest instead of highest (option)

### ISSUE THREAD

**Issue by SoeyKitten** [chalkos/RepairMe#18]
I'd like to see when the lowest spirit% of the equipped gear instead of the highest.

I'm out spiritbonding gathering gear, with the gear gaining spiritbond fairly equally, but not exactly equally, and often have the case that I reach 100% on a couple of pieces, while the rest is 99%. In that case I'd prefer to see the 99% to know I should hit one more node to finish it off before I bother with extracting.

**Comment by PrincessRTFM** [comment]
Personally, I'd kinda like to have both at once, so I can see how close I am to a full bond but also know how far out the slowest one is too.

**Comment by chalkos** [comment]
I'm thinking having this as an option, and showing `min% | max%` for SB text, and having a marker on the bar for the lowest SB

**Comment by chalkos** [comment]
something like this

![image](https://user-images.githubusercontent.com/98429/163669077-5fb27088-b762-4249-a96f-71af7547e137.png)

**Comment by chalkos** [comment]
https://github.com/chalkos/RepairMe/commit/fff24616b7cedc9b8ba646866c9c9e1e79c74d8c - show lowest and highest spiritbonded item

https://github.com/chalkos/RepairMe/commit/5acf5fcb8ab880e856c9e25bd62b9edee704ad35 - show all spiritbond % as lines in the bar

**Comment by chalkos** [comment]
it's here https://github.com/goatcorp/DalamudPlugins/pull/2340
let me know if thats what you had in mind
