### ISSUE TITLE
New positioning system is...

### ISSUE THREAD

**Issue by xShaithx** [chalkos/RepairMe#23]
in a word, awful.

Plugging in coordinates manually attempting to get everything lined up seems like a massive step backwards.  Any chance of a return to the glory days of drag-n-drop positioning?

**Comment by chalkos** [comment]
yup. when this is merged it will be in testing https://github.com/goatcorp/DalamudPlugins/pull/2337
also this one no longer reset position settings

**Comment by xShaithx** [comment]
Thanks, the new version with both options is most excellent so far.  Good
job!
