### ISSUE TITLE
[Bug] Spiritbond complete button doesn't work in german

### ISSUE THREAD

**Issue by Stiopka** [chalkos/RepairMe#25]
![image](https://user-images.githubusercontent.com/73742622/163786379-3d1464a9-53a3-47b1-bc1e-11416bf4938d.png)
i clicked spiritbond complete but the game dont know the command to open the window because my game is on german, maybe adding support for other language.

German: Materia extrahieren
French: Matérialiser
Japanese: マテリア精製

**Comment by chalkos** [comment]
Right.. I didn't even realise the names would be different. thanks for the report. I'll see a way to fix this for all languages and both buttons

**Comment by chalkos** [comment]
Will be in testing when this is merged https://github.com/goatcorp/DalamudPlugins/pull/2393
thanks for reporting the bug!
