### ISSUE TITLE
Changing opacity of alert labels is unclear

### ISSUE THREAD

**Issue by jguluarte** [chalkos/RepairMe#31]
### What's the issue?

I am trying to find the place in settings to adjust the background and opacity of the `Spritbonding Complete` alert, I changed it a couple days ago and cannot for the life of me find it again. 

I'm not sure if this might be related to the bug I just created too, but it doesn't seem obvious when I go to change the background color (which I can do, but do not see any setting in the color selector popup that adjusts opacity).

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and RepairMe.

**Comment by chalkos** [comment]
> when I go to change the background color (which I can do, but do not see any setting in the color selector popup that adjusts opacity)
can you show a screenshot of this part? could be related to your font size, but it's odd that you found it before and cant now
