### ISSUE TITLE
not working in latest patch

### ISSUE THREAD

**Issue by comprido** [chalkos/RepairMe#33]
### What are you trying to do?

hey man,
I want to thank you for your great addon, it's very useful.

I would like to know if you plan to update it to be able to work in the latest patch. "doesn't work now, and I miss it :)"

Thanks,

### What is the expected behavior?

that it works like was before the patch

### What actually happened?

a new patch was released

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and RepairMe.

**Comment by chalkos** [comment]
it's pending approval now and should be available soon
