### ISSUE TITLE
Food buff reminder.

### ISSUE THREAD

**Issue by eaganlai** [chalkos/RepairMe#35]
### What's your suggestion?

I am dumb and I forget food buffs a lot (especially during leveling jobs). Maybe I can get a "EAT FOOD YOU DUMB ASS!!" at the middle of my screen to fix my dumbness. A reminder depending on the remaining food buff timer would be appreciated!

**Comment by chalkos** [comment]
That's exactly the kind of thing this does https://github.com/MidoriKami/NoTankYou (just need to **wait** for it to be updated)
