### ISSUE TITLE
Set x/y position of HUD elements

### ISSUE THREAD

**Issue by nivomi** [chalkos/RepairMe#4]
It'd be nice to be able to set the x/y position of HUD elements via a text field instead of clicking and dragging. Trying to line stuff up is a bit fiddly with a mouse.

**Comment by chalkos** [comment]
Also include a way to reset to default position

**Comment by chalkos** [comment]
This will be in testing when this PR is accepted https://github.com/goatcorp/DalamudPlugins/pull/2301
Note that loading this version will erase your position settings and you'll need to reposition everything again using the new position sliders.

**Comment by chalkos** [comment]
https://github.com/goatcorp/DalamudPlugins/pull/2337
this one no longer reset position settings
