### ISSUE TITLE
Durability bar stuck in top left corner

### ISSUE THREAD

**Issue by Dekartea** [chalkos/RepairMe#5]
Can't be moved, can't be changed, doesn't display element correctly (big black/red bar instead of the actual durability bar)
Have completely removed and reinstalled RepairMe from my system multiple times, manually deleting the relevant files from my appdata folder. Even tried messing with the dalamudUI.ini and seeing if I could reposition the durability bar through it. Nothing has changed. Please help! Love this plugin.
EDIT: Should mention, this first happened after messing with my resolution (went from WBL to fullscreen and back) - a similar issue occurred with the PingPlugin plugin, however I used its "reset window position" function and it now functions perfectly).

![image](https://user-images.githubusercontent.com/90298614/137041786-f85c740d-013e-4550-b179-aa684ff175db.png)
![image](https://user-images.githubusercontent.com/90298614/137041883-1628e133-ce67-4554-86e2-f04213d79050.png)

**Comment by chalkos** [comment]
workaround to fix for now:
open config window, check "Move UI", go fullscreen and back and you should be able to drag the RepairMe windows. They'll in edges of the screen so look for them there

but this seems to be happening outside RepairMe as well. other windows got the same treatment when i tested this

permanent fix will be done in #4
