### ISSUE TITLE
[Suggestion] Decimal comma remover

### ISSUE THREAD

**Issue by RosskoCholakov** [chalkos/RepairMe#6]
I suggest adding the option to shorten the percentage text by lowering the percentage accuracy (removing the decimal comma and the two digits after it). That would enable to enlarge the scale of the number and not having to wonder where to put the 4 digits. I mean who even cares for the bonus accuracy anyway :D

**Comment by chalkos** [comment]
https://github.com/chalkos/RepairMe/commit/99d978a9e3651f3026d13ab7577a3239055c4a99
also added an option to remove the % sign

**Comment by chalkos** [comment]
it's here https://github.com/goatcorp/DalamudPlugins/pull/2340 (available in testing when this is merged)
