### ISSUE TITLE
[Feature Request] Show condition above 100%

### ISSUE THREAD

**Issue by IGP** [chalkos/RepairMe#9]
When self repairing gear via Dark Matter you can repair up to 199.99% condition. It would be nice if the UI was able to display the actual value instead of soft capping at 100% even if all gear is above 100%.

**Comment by bbeenn1** [comment]
I came here just to say the same thing, but still love having the plugin!

**Comment by chalkos** [comment]
It will be available for testing once this PR is merged: https://github.com/goatcorp/DalamudPlugins/pull/1426
